# Generated by Django 4.2.4 on 2023-09-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=256)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
