# Generated by Django 4.2.4 on 2023-09-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='name',
        ),
    ]
