# Generated by Django 4.2.4 on 2023-09-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='nickname', max_length=200),
            preserve_default=False,
        ),
    ]
