# Generated by Django 4.2.4 on 2023-09-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[(0, 'NORESPONSE'), (1, 'ADVANCE'), (2, 'REJECT')], default=0, max_length=2),
        ),
    ]
