# Generated by Django 4.2.4 on 2023-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[(0, 'NORESPONSE'), (1, 'ADVANCE'), (2, 'REJECT')], default='NORESPONSE', max_length=2),
        ),
    ]
