# Generated by Django 4.2.4 on 2023-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('N', 'No Response'), ('A', 'Advancing'), ('R', 'Rejected')], default='N', max_length=1),
        ),
    ]
